### ISSUE TITLE
Create toggle menu from left to top

### ISSUE THREAD

**Issue by UmairKhalid786** [UmairKhalid786/ComposeTv#106]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Many TV apps support a top-bar menu that makes it easy to navigate 

**Describe alternatives you've considered**
No

**Design motivation**

![Screenshot 2023-10-21 at 00 47 49](https://github.com/UmairKhalid786/ComposeTv/assets/21205138/8cf9ad81-3bc5-4b03-a6d9-aa998e053f37)

**Comment by SeptAlfauzan** [comment]
hey @UmairKhalid786 , could you assign it to me?

**Comment by UmairKhalid786** [comment]
Hello @SeptAlfauzan, thanks for accepting this issue

**Comment by SeptAlfauzan** [comment]
Hey @UmairKhalid786 I want to make sure about this task, is it okay to create the top bar menu component and replace the home drawer component with it, or is it enough just by creating the top bar component without altering existing layout?

**Comment by UmairKhalid786** [comment]
@SeptAlfauzan so we will not replace it with top bar, we keep the existing left menu along with top bar but will give user option to choose from settings, by default left menu will be enabled but if a user want to choose top bar, they can switch from settings

**Comment by SeptAlfauzan** [comment]
okaty noted
