### ISSUE TITLE
App crashes when quickly scrolling HomeCarousel

### ISSUE THREAD

**Issue by VuManhHung97** [UmairKhalid786/ComposeTv#115]
**Describe the bug**
When we quickly scroll up and down the list of HomeCarousel(TVLazyRow in TVLazyColumn) an error will occur.

**To Reproduce**
1. Open App
2. Focus on the list in Home Carousel
3. Scroll down and up quickly and continuously
4. App crash error occurred

**Expected behavior**
I hope there is no app crash error. Because if the scroll is slow, there will be no error if you can handle how to minimize the scroll speed.

**Video**
https://drive.google.com/file/d/1Wir6Py-mKDJVLsSFkWB2TJ8AmNCDIixe/view?usp=sharing

**Comment by UmairKhalid786** [comment]
This issue should be fixed with the latest update, it was in the previous compose version
