### ISSUE TITLE
Featuire request show details screen

### ISSUE THREAD

**Issue by techker** [UmairKhalid786/ComposeTv#40]
Hey, love the example. been wanting to start and with your example it is a great start. i have added a few things but trying to get a details dialog or view to open on clicking the movie?is there a way in this or it needs to be added?

Thx!!

**Comment by UmairKhalid786** [comment]
Hey Mike, thank you so much for reminding me. I will prioritise it and hopefully you will see detail page in next week 🙏✨

**Comment by techker** [comment]
great thx!👍

**Comment by UmairKhalid786** [comment]
@techker A basic product detail page is added. Next week I will push more improvements to this feature.
