### ISSUE TITLE
Trying to uses this project to get started

### ISSUE THREAD

**Issue by MPIIIMan** [UmairKhalid786/ComposeTv#5]
Hey there. Thanks for putting this up. Its like the only sample project for Jetpack + Android TV.
I was trying to use this project to get started using Jetpack Compose and Android TV.
I can't seem to get this project to run after opening.
Following Error: Activity class {com.techlads.composetv/com.techlads.composetv.LoginActivity} does not exist
I definitely see the LoginActivity file. 
Any ideas?

**Comment by MPIIIMan** [comment]
Disregard. Problem with environment.

**Comment by hkarmoush** [comment]
@MPIIIMan Could you mention what the issue was on your end?
