### ISSUE TITLE
Poor performance on scrolling down/up in main page

### ISSUE THREAD

**Issue by svilenrusev** [UmairKhalid786/ComposeTv#84]
The problem is that if we run the app on real device, it is extremely laggy when I scroll down/up, I believe this is known issue, it is related to TvLazyColumn and possibly it`s recycling, do we have a solution for this issue? Have you tried implement BaselineProfiles?

**Comment by UmairKhalid786** [comment]
@svilenrusev True, that is a known issue and we haven't done much for it in favor of the Compose TV SDK being in Alpha state, hopefully, they will improve it. But I will definitely consider it on my priority list.

Thanks for reporting.

**Comment by UmairKhalid786** [comment]
The project now has pointed to the latest alpha10 that contains some core areas as profiled and we can see performance improved. But there are some tips if you want to improve it more, always run release build so that you can have R8 benefits
