### ISSUE TITLE
Version Catalog not implemented properly

### ISSUE THREAD

**Issue by swapnil-musale** [UmairKhalid786/ComposeTv#91]
I have gone through the project gradle files found version catalog is not implemented properly means plugin are also part of libraries block. 

Proposed Solution :
1. As per Version Catalog standard we can segregate libraries, plugins & bundle into their respective blocks.

I would love to work on this implementation if this is still untracked.

**Comment by UmairKhalid786** [comment]
@swapnil-musale Thanks for coming up with a solution,  sounds good. 

Please feel free to raise a PR 😊.

**Comment by swapnil-musale** [comment]
@UmairKhalid786 Found some libraries in version catalog which are not implemented in any of the project module. Did they present intentionally or should I remove them with this change ?

**Comment by UmairKhalid786** [comment]
@swapnil-musale I think timber was in the plan but we can definitely remove unused
